### ISSUE TITLE
IE compatibility?

### ISSUE THREAD

**Issue by dayne** [gina-alaska/ttnmanager#47]

**Comment by teknofire** [comment]
Just tested IE8 and that looks we won't be able to support that version.  The version of jquery that is need for the bootstrap stuff only supports IE9+

I'm still waiting for my IE9 vm to finish downloading so I can test the newer version.

**Comment by teknofire** [comment]
IE9 has a problem with displaying the map image because the data was a jpg and it was being sent as if it was a png.  I've fixed it so the browser now correctly requests a jpg version. 

IE8 users will be able to view the main index page and the map image just fine but will not be able to use the area forms.
